on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  assign_to_project:
    runs-on: ubuntu-latest
    name: Assign a PR to project based on label
    steps:
      - name: Assign to project
        uses: elastic/github-actions/project-assigner@v1.0.2
        id: project_assigner
        with:
          issue-mappings: |
            [
              { "label": "pa_test", "projectName": "Workflow Test", "columnId": 7922444 }
            ]
          ghToken: ${{ secrets.GH_PAT }}
